# Generated by Django 5.0 on 2023-12-21 06:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="tasks",
        ),
    ]
