# Generated by Django 5.0 on 2023-12-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0002_remove_report_tasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="performance",
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
