# Generated by Django 5.0 on 2023-12-20 09:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="roll",
            new_name="role",
        ),
    ]
